name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build frontend
        run: yarn build
      - name: Server side rendering
        run: |
          yarn add --dev react-snap
          yarn react-snap
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEGANYIN_WEBSITE }}'
          projectId: meganyin-website
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
